config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/hero'

  resources :user_sessions, only: %i[new create destroy]

  resources :users, only: %i[show index new create]

  resources :courses do
    resources :course_lessons, only: %i[update destroy]
    resources :enrolments, only: %i[new create destroy update]
    resources :lessons do
      resources :comments
    end
  end

  
  resources :tags
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :create, User
    return unless user.present?

    can :manage, User
    can :manage, Course, author: user
    can :manage, Lesson
    can :manage, Comment
    can :manage, CourseLesson
    can :read, Course
    can :manage, Enrolment
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :lesson

  validates :body, presence: true, length: { minimum: 1 }
end

app/models/course.rb
class Course < ApplicationRecord
  scope :enroled, ->(user_id) { where(id: Enrolment.where(user_id:).pluck(:course_id)) }
  scope :available, ->(user_id) { where.not(id: enroled(user_id)) }
  scope :authored, ->(user_id) { where(author_id: user_id) }

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :course_lessons, dependent: :destroy
  has_many :lessons, -> { order(:position) }, through: :course_lessons
  has_many :enrolments, dependent: :destroy
  has_one_attached :photo
  has_rich_text :description
  validates :title, presence: true, uniqueness: true, length: { minimum: 3 }
  validates :description, presence: true

  def swap_lessons(first_lesson, second_lesson)
    first_pos = first_lesson.position
    second_pos = second_lesson.position
    first_lesson.set_position(second_pos)
    second_lesson.set_position(first_pos)
  end

  def get_course_lesson(lesson)
    course_lessons.find_by(lesson_id: lesson.id)
  end

  def tag_list
    tags.collect(&:name).join(', ')
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(',').collect { |s| s.strip.downcase }.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name:) }
    self.tags = new_or_found_tags
  end
end

app/models/course_lesson.rb
class CourseLesson < ApplicationRecord
  belongs_to :course
  belongs_to :lesson

  def set_position(position)
    self.position = position
    save
  end
end

app/models/enrolment.rb
class Enrolment < ApplicationRecord
  belongs_to :user
  belongs_to :course

  def update_progress(course, position)
    self.progress = (position.to_f / course.lessons.count * 100).to_i
    save
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  has_many :comments, dependent: :destroy
  has_many :course_lessons, dependent: :destroy
  validates :title, presence: true, length: { minimum: 3 }
  has_rich_text :content
  has_one_attached :photo
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :courses, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :authored_courses, class_name: 'Course', foreign_key: 'author_id', dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :enrolments, dependent: :destroy

  validates :username, presence: true, uniqueness: true, length: { minimum: 1 }
  validates :email, presence: true, uniqueness: true, length: { minimum: 3 }
  validates :password, presence: true, length: { minimum: 3 }
  validates :password_confirmation, presence: true

  def enroled?(course)
    enrolments.pluck(:course_id).include?(course.id)
  end

  def get_enrolment(course)
    enrolments.find_by(course_id: course.id)
  end

  def author?(course)
    id == course.author_id
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    redirect_to courses_path(enroled: true) and return if current_user

    redirect_to pages_hero_path
  end

  def hero; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def show; end

  def new; end

  def create
    if @user.save
      flash[:notice] = t(:user_notice)
      redirect_to new_user_session_path
    else
      flash[:alert] = t(:user_alert)
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
  def move_lower
    CourseLesson.swap_lessons(@course.course_lessons.find_by(position: params[:position].to_i),
                              @course.course_lessons.find_by(position: params[:position].to_i - 1))
  end

  def move_higher
    CourseLesson.swap_lessons(@course.course_lessons.find_by(position: params[:position].to_i),
                              @course.course_lessons.find_by(position: params[:position].to_i + 1))
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_courses_helper.rb
module UserCoursesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearningPlatform</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/default.min.css">
  </head>

  <body>
  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>

  <%= yield %>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
  
  <script>
      hljs.configure({"cssSelector": ".trix-content pre"});
      hljs.highlightAll();
  </script>
  </body>
</html>

app/views/pages/_empty.html.erb
<div class="w-full flex items-center flex-wrap justify-center gap-10 mt-20">
  <div class="grid gap-4 w-60 mr-20">
    <svg class="mx-auto" xmlns="http://www.w3.org/2000/svg" width="350" height="350" viewBox="0 0 154 161" fill="none">
      <path d="M0.0616455 84.4268C0.0616455 42.0213 34.435 7.83765 76.6507 7.83765C118.803 7.83765 153.224 42.0055 153.224 84.4268C153.224 102.42 147.026 118.974 136.622 132.034C122.282 150.138 100.367 161 76.6507 161C52.7759 161 30.9882 150.059 16.6633 132.034C6.25961 118.974 0.0616455 102.42 0.0616455 84.4268Z" fill="#EEF2FF" />
      <path d="M96.8189 0.632498L96.8189 0.632384L96.8083 0.630954C96.2034 0.549581 95.5931 0.5 94.9787 0.5H29.338C22.7112 0.5 17.3394 5.84455 17.3394 12.4473V142.715C17.3394 149.318 22.7112 154.662 29.338 154.662H123.948C130.591 154.662 135.946 149.317 135.946 142.715V38.9309C135.946 38.0244 135.847 37.1334 135.648 36.2586L135.648 36.2584C135.117 33.9309 133.874 31.7686 132.066 30.1333C132.066 30.1331 132.065 30.1329 132.065 30.1327L103.068 3.65203C103.068 3.6519 103.067 3.65177 103.067 3.65164C101.311 2.03526 99.1396 0.995552 96.8189 0.632498Z" fill="white" stroke="#E5E7EB" />
      <ellipse cx="80.0618" cy="81" rx="28.0342" ry="28.0342" fill="#EEF2FF" />
      <path d="M99.2393 61.3061L99.2391 61.3058C88.498 50.5808 71.1092 50.5804 60.3835 61.3061C49.6423 72.0316 49.6422 89.4361 60.3832 100.162C71.109 110.903 88.4982 110.903 99.2393 100.162C109.965 89.4363 109.965 72.0317 99.2393 61.3061ZM105.863 54.6832C120.249 69.0695 120.249 92.3985 105.863 106.785C91.4605 121.171 68.1468 121.171 53.7446 106.785C39.3582 92.3987 39.3582 69.0693 53.7446 54.683C68.1468 40.2965 91.4605 40.2966 105.863 54.6832Z" stroke="#E5E7EB" />
      <path d="M110.782 119.267L102.016 110.492C104.888 108.267 107.476 105.651 109.564 102.955L118.329 111.729L110.782 119.267Z" stroke="#E5E7EB" />
      <path d="M139.122 125.781L139.122 125.78L123.313 109.988C123.313 109.987 123.313 109.987 123.312 109.986C121.996 108.653 119.849 108.657 118.521 109.985L118.871 110.335L118.521 109.985L109.047 119.459C107.731 120.775 107.735 122.918 109.044 124.247L109.047 124.249L124.858 140.06C128.789 143.992 135.191 143.992 139.122 140.06C143.069 136.113 143.069 129.728 139.122 125.781Z" fill="#A5B4FC" stroke="#818CF8" />
      <path d="M83.185 87.2285C82.5387 87.2285 82.0027 86.6926 82.0027 86.0305C82.0027 83.3821 77.9987 83.3821 77.9987 86.0305C77.9987 86.6926 77.4627 87.2285 76.8006 87.2285C76.1543 87.2285 75.6183 86.6926 75.6183 86.0305C75.6183 80.2294 84.3831 80.2451 84.3831 86.0305C84.3831 86.6926 83.8471 87.2285 83.185 87.2285Z" fill="#4F46E5" />
      <path d="M93.3528 77.0926H88.403C87.7409 77.0926 87.2049 76.5567 87.2049 75.8946C87.2049 75.2483 87.7409 74.7123 88.403 74.7123H93.3528C94.0149 74.7123 94.5509 75.2483 94.5509 75.8946C94.5509 76.5567 94.0149 77.0926 93.3528 77.0926Z" fill="#4F46E5" />
      <path d="M71.5987 77.0925H66.6488C65.9867 77.0925 65.4507 76.5565 65.4507 75.8945C65.4507 75.2481 65.9867 74.7122 66.6488 74.7122H71.5987C72.245 74.7122 72.781 75.2481 72.781 75.8945C72.781 76.5565 72.245 77.0925 71.5987 77.0925Z" fill="#4F46E5" />
      <rect x="38.3522" y="21.5128" width="41.0256" height="2.73504" rx="1.36752" fill="#4F46E5" />
      <rect x="38.3522" y="133.65" width="54.7009" height="5.47009" rx="2.73504" fill="#A5B4FC" />
      <rect x="38.3522" y="29.7179" width="13.6752" height="2.73504" rx="1.36752" fill="#4F46E5" />
      <circle cx="56.13" cy="31.0854" r="1.36752" fill="#4F46E5" />
      <circle cx="61.6001" cy="31.0854" r="1.36752" fill="#4F46E5" />
      <circle cx="67.0702" cy="31.0854" r="1.36752" fill="#4F46E5" />
    </svg>
    <div>
      <h2 class="text-center text-black text-xl font-semibold leading-loose pb-2"><%= "#{t :no_courses}"%></h2>
      <p class="text-center text-black text-base font-normal leading-relaxed pb-4"><%= "#{t :change_filters}"%> <br />
        <%= "#{t :see_courses}"%> </p>
      <div class="flex gap-3">
        <%= link_to "#{t :create_course}", new_course_path(available: true), class:"text-center w-full px-3 py-2 bg-indigo-600 hover:bg-indigo-700
         transition-all duration-500 rounded-full text-white text-xs font-semibold leading-4" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/_navbar.html.erb
<section class="px-8 text-gray-700 bg-indigo-500 w-full mx-auto">
  <div class="container flex flex-col items-center justify-between py-5 md:flex-row mx-auto">
    <div class="relative flex flex-col md:flex-row mx-auto">
      <nav class="flex-1 flex-row items-center mb-5 text-base md:mb-0 md:pl-8 md:ml-8 ">
        <a href="#_" class="inline-flex mr-5 items-center mb-5 font-medium text-gray-900 lg:w-auto lg:items-center lg:justify-center md:mb-0">
          <span class="mx-auto text-xl font-black leading-none text-gray-900 select-none"><%= t :learning_platform %></span>
        </a>
        <% if current_user %>
          <%= link_to "#{t :explore}", courses_path(available: true), class: "rounded-md px-4 py-2 text-black hover:text-white hover:bg-indigo-600 transition duration-300 font-medium" %>
          <%= link_to "#{t :my_learning}", courses_path(enroled: true), class: "rounded-md px-4 py-2 text-black hover:text-white hover:bg-indigo-600 transition duration-300 font-medium" %>
          <%= link_to "#{t :my_courses}", courses_path(authored: true), class: "rounded-md px-4 py-2 text-black hover:text-white hover:bg-indigo-600 transition duration-300 font-medium" %>

          <div class="relative inline-block text-left">
            <div class="group py-1">
              <button type="button"
                class="inline-flex justify-center items-center w-full px-4 py-2 text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:bg-indigo-700 rounded-lg transition duration-300">
                <%= current_user.username %>
                <svg class="w-4 h-4 ml-2 -mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M10 12l-5-5h10l-5 5z" />
                </svg>
              </button>
              <div class="absolute left-0 w-40 mt-1 origin-top-left bg-white divide-y divide-gray-100 rounded-md shadow-lg opacity-0 invisible group-hover:opacity-100 group-hover:visible transition duration-300 z-50">
                <div class="px-4 py-3 text-sm text-gray-900 dark:text-white">
                  <div class="font-medium truncate"><%= current_user.email %></div>
                </div>
                <div class="py-1">
                  <%= link_to "#{t :profile}", user_path(current_user), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 transition duration-300" %>
                  <%= link_to "#{t :log_out}", user_session_path(current_user), data: { turbo_method: :delete }, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 transition duration-300" %>
                </div>
              </div>
            </div>
          </div>
        <% else %>
          <%= link_to "#{t :home}", root_path, class: "rounded-md px-4 py-2 text-black hover:text-white hover:bg-indigo-600 transition duration-300 font-medium" %>
          <%= link_to "#{t :log_in}", new_user_session_path, class: "text-white bg-gray-600 hover:bg-gray-700 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 transition duration-300" %>
          <%= link_to "#{t :sign_up}", new_user_path, class: "text-white bg-indigo-600 hover:bg-indigo-700 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 transition duration-300" %>
        <% end %>
        <%= link_to root_path(locale: :ro) do %>
          <svg class="inline-flex w-8 h-8 mx-2 hover:opacity-80 transition duration-300" enable-background="new 0 0 512 512" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
            <path d="m345.043 15.922c-27.734-10.289-57.729-15.922-89.043-15.922-31.314-.001-61.31 5.633-89.043 15.922l-22.261 240.077 22.261 240.077c27.732 10.292 57.728 15.924 89.043 15.924 31.313 0 61.31-5.632 89.043-15.924l22.26-240.076z" fill="#ffda44"/>
            <path d="m512 256c0-110.07-69.472-203.907-166.957-240.077v480.156c97.485-36.174 166.956-130.007 166.957-240.079z" fill="#d80027"/>
            <path d="m0 255.999c0 110.073 69.472 203.906 166.955 240.079l.001-480.154c-97.484 36.17-166.956 130.004-166.956 240.075z" fill="#0052b4"/>
          </svg>
        <% end %>
        <%= link_to root_path(locale: :en) do %>
          <svg class="inline-flex w-8 h-8 hover:opacity-80 transition duration-300" enable-background="new 0 0 512 512" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
            <circle cx="256" cy="256" fill="#f0f0f0" r="256"/>
            <path d="m244.87 256h267.13c0-23.106-3.08-45.49-8.819-66.783h-258.311z" fill="#d80027"/>
            <path d="m244.87 122.435h229.556c-15.671-25.572-35.708-48.175-59.07-66.783h-170.486z" fill="#d80027"/>
            <path d="m256 512c60.249 0 115.626-20.824 159.356-55.652h-318.712c43.73 34.828 99.107 55.652 159.356 55.652z" fill="#d80027"/>
            <path d="m37.574 389.565h436.852c12.581-20.529 22.338-42.969 28.755-66.783h-494.362c6.417 23.814 16.174 46.254 28.755 66.783z" fill="#d80027"/>
            <path d="m118.584 39.978h23.329l-21.7 15.765 8.289 25.509-21.699-15.765-21.699 15.765 7.16-22.037c-19.106 15.915-35.852 34.561-49.652 55.337h7.475l-13.813 10.035c-2.152 3.59-4.216 7.237-6.194 10.938l6.596 20.301-12.306-8.941c-3.059 6.481-5.857 13.108-8.372 19.873l7.267 22.368h26.822l-21.7 15.765 8.289 25.509-21.699-15.765-12.998 9.444c-1.301 10.458-1.979 21.11-1.979 31.921h256c0-141.384 0-158.052 0-256-50.572 0-97.715 14.67-137.416 39.978zm9.918 190.422-21.699-15.765-21.699 15.765 8.289-25.509-21.7-15.765h26.822l8.288-25.509 8.288 25.509h26.822l-21.7 15.765zm-8.289-100.083 8.289 25.509-21.699-15.765-21.699 15.765 8.289-25.509-21.7-15.765h26.822l8.288-25.509 8.288 25.509h26.822zm100.115 100.083-21.699-15.765-21.699 15.765 8.289-25.509-21.7-15.765h26.822l8.288-25.509 8.288 25.509h26.822l-21.7 15.765zm-8.289-100.083 8.289 25.509-21.699-15.765-21.699 15.765 8.289-25.509-21.7-15.765h26.822l8.288-25.509 8.288 25.509h26.822zm0-74.574 8.289 25.509-21.699-15.765-21.699 15.765 8.289-25.509-21.7-15.765h26.822l8.288-25.509 8.288 25.509h26.822z" fill="#0052b4"/>
          </svg>
        <% end %>
      </nav>
    </div>
  </div>
</section>

app/views/pages/hero.html.erb
<%= render 'pages/navbar' %>

<section class="px-2 py-32 bg-white md:px-0">
  <div class="container items-center max-w-6xl px-8 mx-auto xl:px-5">
    <div class="flex flex-wrap items-center sm:-mx-3">
      <div class="w-full md:w-1/2 md:px-3">
        <div class="w-full pb-6 space-y-6 sm:max-w-md lg:max-w-lg md:space-y-4 lg:space-y-8 xl:space-y-9 sm:pr-5 lg:pr-0 md:pb-0">
          <h1 class="text-4xl font-extrabold tracking-tight text-gray-900 sm:text-5xl md:text-4xl lg:text-5xl xl:text-6xl">
            <span class="block xl:inline"><%= t :courses_demand %></span><br>
            <span class="block text-indigo-600 xl:inline"><%= t :choose_topics %></span>
          </h1>
          <p class="mx-auto text-base text-gray-500 sm:max-w-md lg:text-xl md:max-w-3xl"><%= t :register_to %></p>
          <div class="relative flex flex-col sm:flex-row sm:space-x-4">
            <%= link_to new_user_path, class:"flex items-center w-full px-6 py-3 mb-3 text-lg text-white bg-indigo-600 rounded-md sm:mb-0 hover:bg-indigo-700 sm:w-auto" do %>
              <%= t :try_free %>
              <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 ml-1" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
               stroke-linecap="round" stroke-linejoin="round"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>
            <% end %>
          </div>
        </div>
      </div>
      <div class="w-full md:w-1/2">
        <div class="w-full h-auto overflow-hidden rounded-md shadow-xl sm:rounded-xl">
          <img src="https://images.unsplash.com/photo-1498049860654-af1a5c566876?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80">
        </div>
      </div>
    </div>
  </div>
</section>