config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/hero'

  resources :user_sessions, only: %i[new create destroy]

  resources :users, only: %i[show index new create]

  resources :courses do
    resources :course_lessons, only: %i[update destroy]
    resources :enrolments, only: %i[new create destroy update]
    resources :lessons do
      resources :comments
    end
  end

  
  resources :tags
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :create, User
    return unless user.present?

    can :manage, User
    can :manage, Course, author: user
    can :manage, Lesson
    can :manage, Comment
    can :manage, CourseLesson
    can :read, Course
    can :manage, Enrolment
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :lesson

  validates :body, presence: true, length: { minimum: 1 }
end

app/models/course.rb
class Course < ApplicationRecord
  scope :enroled, ->(user_id) { where(id: Enrolment.where(user_id:).pluck(:course_id)) }
  scope :available, ->(user_id) { where.not(id: enroled(user_id)) }
  scope :authored, ->(user_id) { where(author_id: user_id) }

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :course_lessons, dependent: :destroy
  has_many :lessons, -> { order(:position) }, through: :course_lessons
  has_many :enrolments, dependent: :destroy
  has_one_attached :photo
  has_rich_text :description
  validates :title, presence: true, uniqueness: true, length: { minimum: 3 }
  validates :description, presence: true

  def swap_lessons(first_lesson, second_lesson)
    first_pos = first_lesson.position
    second_pos = second_lesson.position
    first_lesson.set_position(second_pos)
    second_lesson.set_position(first_pos)
  end

  def get_course_lesson(lesson)
    course_lessons.find_by(lesson_id: lesson.id)
  end

  def tag_list
    tags.collect(&:name).join(', ')
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(',').collect { |s| s.strip.downcase }.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name:) }
    self.tags = new_or_found_tags
  end
end

app/models/course_lesson.rb
class CourseLesson < ApplicationRecord
  belongs_to :course
  belongs_to :lesson

  def set_position(position)
    self.position = position
    save
  end
end

app/models/enrolment.rb
class Enrolment < ApplicationRecord
  belongs_to :user
  belongs_to :course

  def update_progress(course, position)
    self.progress = (position.to_f / course.lessons.count * 100).to_i
    save
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  has_many :comments, dependent: :destroy
  has_many :course_lessons, dependent: :destroy
  validates :title, presence: true, length: { minimum: 3 }
  has_rich_text :content
  has_one_attached :photo
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :courses, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :authored_courses, class_name: 'Course', foreign_key: 'author_id', dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :enrolments, dependent: :destroy

  validates :username, presence: true, uniqueness: true, length: { minimum: 1 }
  validates :email, presence: true, uniqueness: true, length: { minimum: 3 }
  validates :password, presence: true, length: { minimum: 3 }
  validates :password_confirmation, presence: true

  def enroled?(course)
    enrolments.pluck(:course_id).include?(course.id)
  end

  def get_enrolment(course)
    enrolments.find_by(course_id: course.id)
  end

  def author?(course)
    id == course.author_id
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  load_and_authorize_resource :course
  load_and_authorize_resource :enrolment, through: :course
  load_and_authorize_resource :lesson, through: :course

  def index; end

  def show
    @course_lesson = @course.course_lessons.find_by(lesson_id: @lesson.id)
  end

  def new; end

  def create
    if @lesson.save
      @course.course_lessons.create(course_id: @course.id, lesson_id: @lesson.id,
                                    position: @course.course_lessons.count)
      flash[:notice] = t(:lesson_notice)
      redirect_to course_lessons_path(@course)
    else
      flash[:alert] = t(:lesson_alert)
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @lesson.update(lesson_params)
      flash[:notice] = t(:lesson_update_notice)
      redirect_to course_lessons_path(@course)
    else
      flash[:alert] = t(:lesson_update_alert)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @lesson.destroy
    flash[:notice] = t(:lesson_destroy_notice)
    redirect_to courses_path(authored: true)
  end

  protected

  def lesson_params
    params.require(:lesson).permit(:title, :photo, :content, :course_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    redirect_to courses_path(enroled: true) and return if current_user

    redirect_to pages_hero_path
  end

  def hero; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def show; end

  def new; end

  def create
    if @user.save
      flash[:notice] = t(:user_notice)
      redirect_to new_user_session_path
    else
      flash[:alert] = t(:user_alert)
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
  def move_lower
    CourseLesson.swap_lessons(@course.course_lessons.find_by(position: params[:position].to_i),
                              @course.course_lessons.find_by(position: params[:position].to_i - 1))
  end

  def move_higher
    CourseLesson.swap_lessons(@course.course_lessons.find_by(position: params[:position].to_i),
                              @course.course_lessons.find_by(position: params[:position].to_i + 1))
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/user_courses_helper.rb
module UserCoursesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/lessons/_index.html.erb
<div class="flex">
  <div class="flex flex-wrap justify-center gap-4 max-w-5xl mx-auto">
  </div>
  <body class="antialiased font-sans ">
    <div class="container mx-auto px-4 sm:px-8">
      <div class="py-8">
        <div>
          <h2 class="text-2xl font-semibold leading-tight"><%="#{@course.title}#{" lessons"}"%></h2>
        </div>
        <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
          <div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
            <table class="min-w-full leading-normal">
              <thead>
                <tr>
                  <th
                                    class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                    Lesson
                  </th>
                  <th
                                    class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                    Created at
                  </th>
                  <th
                                    class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                    Comments
                  </th>
                  <th
                                    class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody>
                <% @course.lessons.each do |lesson| %>
                  <tr>
                    <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                      <div class="flex items-center">
                        <% if lesson.photo.representable? %>
                          <%= image_tag url_for(lesson.photo), class: "object-cover rounded-md mr-3", width: 100, height: 60 %>
                        <% end %>
                        <p class="text-gray-900 whitespace-no-wrap">
                          <%= lesson.title %>
                        </p>
                      </div>
                    </td>
                    <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                      <p class="text-gray-900 whitespace-no-wrap">
                        <%= lesson.created_at %>
                      </p>
                    </td>
                    <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                      <p class="text-gray-900 whitespace-no-wrap">
                        <%= lesson.comments.count %>
                      </p>
                    </td>
                    <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                      <div class="inline-flex">
                        <div class="flex flex-col">
                          <% course_lesson = @course.get_course_lesson(lesson) %>
                          <%= link_to course_course_lesson_path(@course, course_lesson, position: course_lesson.position, up: true), data: {turbo_method: :put} do %>
                            <svg fill="#000000" height="26px" width="32px" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 330 330" xml:space="preserve" transform="rotate(0)"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier">
                                <path id="XMLID_224_" d="M325.606,229.393l-150.004-150C172.79,76.58,168.974,75,164.996,75c-3.979,0-7.794,1.581-10.607,4.394 l-149.996,150c-5.858,5.858-5.858,15.355,0,21.213c5.857,5.857,15.355,5.858,21.213,0l139.39-139.393l139.397,139.393 C307.322,253.536,311.161,255,315,255c3.839,0,7.678-1.464,10.607-4.394C331.464,244.748,331.464,235.251,325.606,229.393z"></path> </g></svg>
                          <% end %>
                          <%= link_to course_course_lesson_path(@course, course_lesson, position: course_lesson.position, down: true), data: {turbo_method: :put} do %>
                            <svg fill="#000000" height="26px" width="32px" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 330 330" xml:space="preserve" transform="rotate(180)"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path id="XMLID_224_" d="M325.606,229.393l-150.004-150C172.79,76.58,168.974,75,164.996,75c-3.979,0-7.794,1.581-10.607,4.394 l-149.996,150c-5.858,5.858-5.858,15.355,0,21.213c5.857,5.857,15.355,5.858,21.213,0l139.39-139.393l139.397,139.393 C307.322,253.536,311.161,255,315,255c3.839,0,7.678-1.464,10.607-4.394C331.464,244.748,331.464,235.251,325.606,229.393z"></path> </g></svg>
                          <% end %>
                        </div>
                        <div class="flex flex-inline my-auto">
                          <%= link_to edit_course_lesson_path(@course, lesson), class: "ml-4" do %>
                            <svg width="32px" height="32px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier">
                                <path fill-rule="evenodd" clip-rule="evenodd" d="M20.8477 1.87868C19.6761 0.707109 17.7766 0.707105 16.605 1.87868L2.44744 16.0363C2.02864 16.4551 1.74317 16.9885 1.62702 17.5692L1.03995 20.5046C0.760062 21.904 1.9939 23.1379 3.39334 22.858L6.32868 22.2709C6.90945 22.1548 7.44285 21.8693 7.86165 21.4505L22.0192 7.29289C23.1908 6.12132 23.1908 4.22183 22.0192 3.05025L20.8477 1.87868ZM18.0192 3.29289C18.4098 2.90237 19.0429 2.90237 19.4335 3.29289L20.605 4.46447C20.9956 4.85499 20.9956 5.48815 20.605 5.87868L17.9334 8.55027L15.3477 5.96448L18.0192 3.29289ZM13.9334 7.3787L3.86165 17.4505C3.72205 17.5901 3.6269 17.7679 3.58818 17.9615L3.00111 20.8968L5.93645 20.3097C6.13004 20.271 6.30784 20.1759 6.44744 20.0363L16.5192 9.96448L13.9334 7.3787Z" fill="indigo"></path> </g></svg>
                          <% end %>
                          <%= link_to course_course_lesson_path(@course, course_lesson), data: {turbo_method: :delete}, class: "ml-4" do %>
                            <svg width="32px" height="32px" viewBox="0 -0.5 21 21" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <title>delete [#1487]</title> <desc>Created with Sketch.</desc> <defs> </defs> <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"> <g id="Dribbble-Light-Preview" transform="translate(-179.000000, -360.000000)" fill="red"> <g id="icons" transform="translate(56.000000, 160.000000)"> <path d="M130.35,216 L132.45,216 L132.45,208 L130.35,208 L130.35,216 Z M134.55,216 L136.65,216 L136.65,208 L134.55,208 L134.55,216 Z M128.25,218 L138.75,218 L138.75,206 L128.25,206 L128.25,218 Z M130.35,204 L136.65,204 L136.65,202 L130.35,202 L130.35,204 Z M138.75,204 L138.75,200 L128.25,200 L128.25,204 L123,204 L123,206 L126.15,206 L126.15,220 L140.85,220 L140.85,206 L144,206 L144,204 L138.75,204 Z" id="delete-[#1487]"> </path> </g> </g> </g> </g></svg>
                          <% end %>
                        </div>
                      </div>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/lessons/_timeline.html.erb
<!-- component -->
<div class="flex-3 bg-white rounded-lg shadow-xl mt-4 p-8 sticky top-0">
  <div class="px-4 sticky top-0">
    <h4 class="text-xl text-gray-900 font-bold">Activity log</h4>
    <div class="absolute h-full border border-dashed border-opacity-20 border-secondary"></div>
    <!-- start::Timeline item -->
    <div class="flex items-center  my-6 -ml-1.5">
      <div class="w-1/12 z-10">
        <div class="w-3.5 h-3.5 bg-blue-600 rounded-full"></div>
      </div>
      <div class="w-11/12">
        <p class="text-sm">Profile informations changed.</p>
        <p class="text-xs text-gray-500">3 min ago</p>
      </div>
    </div>
    <!-- end::Timeline item -->
    <!-- start::Timeline item -->
    <div class="flex items-center w-full my-6 -ml-1.5">
      <div class="w-1/12 z-10">
        <div class="w-3.5 h-3.5 bg-blue-600 rounded-full"></div>
      </div>
      <div class="w-11/12">
        <p class="text-sm">
          Connected with <a href="#" class="text-blue-600 font-bold">Colby Covington</a>.</p>
        <p class="text-xs text-gray-500">15 min ago</p>
      </div>
    </div>
    <!-- end::Timeline item -->
    <!-- start::Timeline item -->
    <div class="flex items-center w-full my-6 -ml-1.5">
      <div class="w-1/12 z-10">
        <div class="w-3.5 h-3.5 bg-blue-600 rounded-full"></div>
      </div>
      <div class="w-11/12">
        <p class="text-sm">Invoice <a href="#" class="text-blue-600 font-bold">#4563</a> was created.</p>
        <p class="text-xs text-gray-500">57 min ago</p>
      </div>
    </div>
    <!-- end::Timeline item -->
    <!-- start::Timeline item -->
    <div class="flex items-center w-full my-6 -ml-1.5">
      <div class="w-1/12 z-10">
        <div class="w-3.5 h-3.5 bg-blue-600 rounded-full"></div>
      </div>
      <div class="w-11/12">
        <p class="text-sm">
          Message received from <a href="#" class="text-blue-600 font-bold">Cecilia Hendric</a>.</p>
        <p class="text-xs text-gray-500">1 hour ago</p>
      </div>
    </div>
    <!-- end::Timeline item -->
    <!-- start::Timeline item -->
    <div class="flex items-center w-full my-6 -ml-1.5">
      <div class="w-1/12 z-10">
        <div class="w-3.5 h-3.5 bg-blue-600 rounded-full"></div>
      </div>
      <div class="w-11/12">
        <p class="text-sm">New order received <a href="#" class="text-blue-600 font-bold">#OR9653</a>.</p>
        <p class="text-xs text-gray-500">2 hours ago</p>
      </div>
    </div>
    <!-- end::Timeline item -->
    <!-- start::Timeline item -->
    <div class="flex items-center w-full my-6 -ml-1.5">
      <div class="w-1/12 z-10">
        <div class="w-3.5 h-3.5 bg-blue-600 rounded-full"></div>
      </div>
      <div class="w-11/12">
        <p class="text-sm">
          Message received from <a href="#" class="text-blue-600 font-bold">Jane Stillman</a>.</p>
        <p class="text-xs text-gray-500">2 hours ago</p>
      </div>
    </div>
    <!-- end::Timeline item -->
  </div>
</div>

app/views/lessons/edit.html.erb
<%= render 'pages/navbar' %>
<div class="flex">
  <%= render 'courses/sidebar' %>
  <div class="flex-1 px-8 py-8">
    <div class="bg-white border-4 rounded-lg shadow">
      <%= form_for [ @course, @lesson ] do |f| %>
        <div class="flex items-start justify-between p-5 border-b rounded-t sticky top-0 bg-gray-100">
          <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl"><%= "#{t :edit}#{@lesson.title}" %></h1>
        </div>
        <% if @lesson.errors.any? %>
          <div class="mb-6">
            <ul>
              <% @lesson.errors.full_messages.each do |message| %>
                <li>
                  <%= message %>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="p-6 space-y-6">
          <div class="grid grid-cols-6 gap-6">
            <div class="col-span-6 sm:col-span-3">
              <%= f.label :title, class:"block text-sm mb-2 font-medium text-gray-900" %>
              <%= f.text_field :title, class:"bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" %>
            </div>
            <div class="col-span-6 sm:col-span-3">
              <%= f.label :photo, class:"block text-sm mb-2 font-medium text-gray-900" %>
              <%= f.file_field :photo, class:"bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" %>
            </div>
            <div class="col-span-full mb-20">
              <%= f.label :content, class:"block text-sm mb-2 font-medium text-gray-900" %>
              <%= f.rich_text_area :content, class:"bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full h-full p-4" %>
            </div>
            <%= f.text_field :course_id, type: "hidden", value: @course&.id %>
          </div>
          <div class="p-6 border-t border-gray-200 rounded-b w-1/3 mx-auto flex justify-center">
            <%= f.submit "#{t :edit_lesson}", class:"flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lessons/show.html.erb
<%= render 'pages/navbar' %>
<div class="flex">
  <%= render 'timeline', lesson: @lesson %>
  <div class="flex-3 px-8 py-8">
    <div class="flex justify-center items-center min-h-screen shadow-lg">
      <div class="content-center px-4 py-8 bg-white rounded-lg shadow border-4">
        <%= @lesson.content %>
        <div class="mt-8 flex justify-center">
          <% if @course_lesson.position == @course.lessons.size - 1 %>
            <% if @course.lessons.size == 1 %>
              <%= link_to "Back", course_path(@course), class:"inline-flex items-center border border-indigo-300 px-3 py-1.5 rounded-md text-indigo-500 hover:bg-indigo-50 text-lg" %>
            <% else %>
              <%= link_to "Back", course_lesson_path(@course, @course.course_lessons.find_by(position: @course_lesson.position - 1).lesson), class:"inline-flex items-center border border-indigo-300 px-3 py-1.5 rounded-md text-indigo-500 hover:bg-indigo-50 text-lg" %>
            <% end %>
            <% if current_user.enroled?(@course) %>
              <%= link_to "Finish", course_enrolment_path(@course, @course.enrolments.find_by(user_id: current_user.id), position: @course_lesson.position + 1),
            data: { turbo_method: :put }, class:"inline-flex items-center border border-indigo-300 px-3 py-1.5 rounded-md text-indigo-500 hover:bg-indigo-50 text-lg" %>
            <% else %>
              <%= link_to "Finish", courses_path(enroled: true), class:"inline-flex items-center border border-indigo-300 px-3 py-1.5 rounded-md text-indigo-500 hover:bg-indigo-50 text-lg" %>
            <% end %>
          <% elsif @course_lesson.position == 0 %>
            <%= link_to "Back", course_path(@course), class:"inline-flex items-center border border-indigo-300 px-3 py-1.5 rounded-md text-indigo-500 hover:bg-indigo-50 text-lg" %>
            <% if current_user.enroled?(@course) %>
              <%= link_to "Next", course_enrolment_path(@course, @course.enrolments.find_by(user_id: current_user.id), position: @course_lesson.position + 1),
            data: { turbo_method: :put }, class:"inline-flex items-center border border-indigo-300 px-3 py-1.5 rounded-md text-indigo-500 hover:bg-indigo-50 text-lg" %>
            <% else %>
              <%= link_to "Next", course_lesson_path(@course, @course.course_lessons.find_by(position: @course_lesson.position + 1).lesson),
            class:"inline-flex items-center border border-indigo-300 px-3 py-1.5 rounded-md text-indigo-500 hover:bg-indigo-50 text-lg" %>
            <% end %>
          <% else %>
            <%= link_to "Back", course_lesson_path(@course, @course.course_lessons.find_by(position: @course_lesson.position - 1).lesson),
          class:"inline-flex items-center border border-indigo-300 px-3 py-1.5 rounded-md text-indigo-500 hover:bg-indigo-50 text-lg" %>
            <% if current_user.enroled?(@course) %>
              <%= link_to "Next", course_enrolment_path(@course, @course.enrolments.find_by(user_id: current_user.id), position: @course_lesson.position + 1),
            data: { turbo_method: :put }, class:"inline-flex items-center border border-indigo-300 px-3 py-1.5 rounded-md text-indigo-500 hover:bg-indigo-50 text-lg" %>
            <% else %>
              <%= link_to "Next", course_lesson_path(@course, @course.course_lessons.find_by(position: @course_lesson.position + 1).lesson),
            class:"inline-flex items-center border border-indigo-300 px-3 py-1.5 rounded-md text-indigo-500 hover:bg-indigo-50 text-lg" %>
            <% end %>
          <% end %>
        </div>
        <div class="bg-gray-100 p-6 mt-10 rounded-lg">
          <h2 class="text-lg font-bold mb-4">Comments</h2>
          <div class="flex flex-col space-y-4">
            <% @lesson.comments.each do |comment| %>
              <div class="bg-white p-4 rounded-lg shadow-md">
                <h3 class="text-lg font-bold"><%= comment.user.username %></h3>
                <p class="text-gray-700 text-sm mb-2">Posted on <%= comment.created_at %></p>
                <p class="text-gray-700"><%= comment.body %></p>
              </div>
            <% end %>
            <div class="bg-white p-4 rounded-lg shadow-md">
              <h3 class="text-lg font-bold mb-2">Add a comment</h3>
              <%= form_with model: [ @course, @lesson, @lesson.comments.build ] do |f| %>
                <div class="mb-4">
                  <%= f.label :body, class:"block text-gray-700 font-bold mb-2" %>
                  <%= f.text_area :body, rows: 5, class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder:"Enter your comment" %>
                </div>
                <%= f.text_field :user_id, type: "hidden", value: current_user&.id %>
                <%= f.text_field :lesson_id, type: "hidden", value: @lesson&.id %>
                <%= f.submit "Submit", class:"bg-indigo-700 hover:bg-indigo-900 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>