config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/hero'

  resources :user_sessions, only: %i[new create destroy]

  resources :users, only: %i[show index new create]

  resources :courses do
    resources :course_lessons, only: %i[update destroy]
    resources :enrolments, only: %i[new create destroy update]
    resources :lessons do
      resources :comments
    end
  end

  
  resources :tags
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :create, User
    return unless user.present?

    can :manage, User
    can :manage, Course, author: user
    can :manage, Lesson
    can :manage, Comment
    can :manage, CourseLesson
    can :read, Course
    can :manage, Enrolment
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :lesson

  validates :body, presence: true, length: { minimum: 1 }
end

app/models/course.rb
class Course < ApplicationRecord
  scope :enroled, ->(user_id) { where(id: Enrolment.where(user_id:).pluck(:course_id)) }
  scope :available, ->(user_id) { where.not(id: enroled(user_id)) }
  scope :authored, ->(user_id) { where(author_id: user_id) }

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :course_lessons, dependent: :destroy
  has_many :lessons, -> { order(:position) }, through: :course_lessons
  has_many :enrolments, dependent: :destroy
  has_one_attached :photo
  has_rich_text :description
  validates :title, presence: true, uniqueness: true, length: { minimum: 3 }
  validates :description, presence: true

  def swap_lessons(first_lesson, second_lesson)
    first_pos = first_lesson.position
    second_pos = second_lesson.position
    first_lesson.set_position(second_pos)
    second_lesson.set_position(first_pos)
  end

  def get_course_lesson(lesson)
    course_lessons.find_by(lesson_id: lesson.id)
  end

  def tag_list
    tags.collect(&:name).join(', ')
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(',').collect { |s| s.strip.downcase }.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name:) }
    self.tags = new_or_found_tags
  end
end

app/models/course_lesson.rb
class CourseLesson < ApplicationRecord
  belongs_to :course
  belongs_to :lesson

  def set_position(position)
    self.position = position
    save
  end
end

app/models/enrolment.rb
class Enrolment < ApplicationRecord
  belongs_to :user
  belongs_to :course

  def update_progress(course, position)
    self.progress = (position.to_f / course.lessons.count * 100).to_i
    save
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  has_many :comments, dependent: :destroy
  has_many :course_lessons, dependent: :destroy
  validates :title, presence: true, length: { minimum: 3 }
  has_rich_text :content
  has_one_attached :photo
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :courses, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :authored_courses, class_name: 'Course', foreign_key: 'author_id', dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :enrolments, dependent: :destroy

  validates :username, presence: true, uniqueness: true, length: { minimum: 1 }
  validates :email, presence: true, uniqueness: true, length: { minimum: 3 }
  validates :password, presence: true, length: { minimum: 3 }
  validates :password_confirmation, presence: true

  def enroled?(course)
    enrolments.pluck(:course_id).include?(course.id)
  end

  def get_enrolment(course)
    enrolments.find_by(course_id: course.id)
  end

  def author?(course)
    id == course.author_id
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  load_and_authorize_resource :course
  load_and_authorize_resource :course_lesson, through: :course
  load_and_authorize_resource :lesson, through: :course_lesson

  def index
    if params[:search].present?
      @courses = @courses.left_outer_joins(:tags).where('courses.title LIKE :search OR tags.name LIKE :search',
                                                        search: "%#{params[:search]}%").distinct
    end

    if params[:available]
      @courses = @courses.available(current_user.id)
    elsif params[:enroled]
      @courses = @courses.enroled(current_user.id)
    elsif params[:authored]
      @courses = @courses.authored(current_user.id)
    end
  end

  def show; end

  def create
    if @course.save
      flash[:notice] = t(:course_notice)
      redirect_to courses_path(authored: true)
    else
      flash[:alert] = t(:course_alert)
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @course.update(course_params)
      flash[:notice] = t(:course_update_notice)
      redirect_to courses_path(authored: true)
    else
      flash[:alert] = t(:course_alert_notice)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @course.destroy
    flash[:notice] = t(:course_destroy_notice)
    redirect_to courses_path(authored: true)
  end

  protected

  def course_params
    params.require(:course).permit(:title, :photo, :description, :difficulty, :public, :tag_list, :author_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    redirect_to courses_path(enroled: true) and return if current_user

    redirect_to pages_hero_path
  end

  def hero; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def show; end

  def new; end

  def create
    if @user.save
      flash[:notice] = t(:user_notice)
      redirect_to new_user_session_path
    else
      flash[:alert] = t(:user_alert)
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
  def move_lower
    CourseLesson.swap_lessons(@course.course_lessons.find_by(position: params[:position].to_i),
                              @course.course_lessons.find_by(position: params[:position].to_i - 1))
  end

  def move_higher
    CourseLesson.swap_lessons(@course.course_lessons.find_by(position: params[:position].to_i),
                              @course.course_lessons.find_by(position: params[:position].to_i + 1))
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/user_courses_helper.rb
module UserCoursesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/courses/_courses.html.erb
<% if params[:available] %>
  <h6 class="text-center text-3xl font-bold my-5"><%= t :explore %></h6>
<% elsif params[:authored] %>
  <h6 class="text-center text-3xl font-bold my-5"><%= t :my_courses %></h6>
<% elsif params[:enroled] %>
  <h6 class="text-center text-3xl font-bold my-5"><%= t :my_learning %></h6>
<% end %>
<% if courses.blank? %>
  <%= render 'pages/empty' %>
<% else %>
  <%= render 'search_bar' %>
<% end %>
<div class="flex flex-wrap justify-start gap-x-5 gap-y-5 mt-5">
  <% courses.each do |course| %>
    <div class="bg-gray-100 p-5 rounded-lg flex-shrink-0" style="flex-basis: calc(33.3333% - 20px);">
      <h1 class="font-bold text-2xl mb-2 text-center"><%= course.title %></h1>
      <%= render 'difficulty', difficulty: course.difficulty %>
      <% if course.tags.blank? %>
        <div class="inline-flex space-x-2 mb-4">
          <span class="bg-indigo-200 text-indigo-500 text-xs font-semibold px-2 py-1 rounded-full">No tags available</span>
        </div>
      <% else %>
        <% course.tags.each do |tag| %>
          <div class="inline-flex space-x-2 mb-4">
            <span class="bg-indigo-200 text-indigo-500 text-xs font-semibold px-2 py-1 rounded-full"><%= tag.name %></span>
          </div>
        <% end %>
      <% end %>
      <% if course.photo.representable? %>
        <%= link_to course_path(course) do %>
          <div class="mt-4">
            <%= image_tag url_for(course.photo), class: "w-full h-48 object-cover rounded-md" %>
          </div>
        <% end %>
      <% end %>
      <%= render 'progressbar', course: course%>
    </div>
  <% end %>
  <% if params[:authored] && !courses.blank? %>
    <%= link_to new_course_path, class: "bg-white border-2 border-dashed border-gray-300 flex items-center justify-center p-5 rounded-lg text-gray-400 hover:text-indigo-500 hover:border-indigo-500 transition duration-150 ease-in-out", style: "flex-basis: calc(33.3333% - 20px); height: 200px;" do %>
      <div class="flex flex-col items-center">
        <span class="text-5xl font-bold">+</span>
        <span class="mt-2 text-lg font-semibold"><%= t :add_course %></span>
      </div>
    <% end %>
  <% end %>
</div>

app/views/courses/_lessons.html.erb
<div class="flex justify-center"> <!-- Centering the flex container -->
  <div class="flex flex-wrap justify-center gap-4 max-w-5xl w-full mx-auto"> <!-- Using w-full to ensure it occupies full width -->
    <body class="antialiased font-sans ">
      <div class="container mx-auto px-0 sm:px-8"> <!-- Set padding to 0 on the sides -->
        <div class="py-8">
          <div>
            <h2 class="text-2xl font-semibold leading-tight"><%="#{@course.title}#{" lessons"}"%></h2>
          </div>
          <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
            <div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
              <table class="min-w-full leading-normal">
                <thead>
                  <tr>
                    <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                      Lesson
                    </th>
                    <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                      Created at
                    </th>
                    <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                      Comments
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <% @course.lessons.each_with_index do |lesson, index| %>
                    <tr>
                      <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                        <div class="flex items-center">
                          <%= index + 1 %>
                          <% if lesson.photo.representable? %>
                            <%= link_to course_lesson_path(@course, lesson) do %>
                              <%= image_tag url_for(lesson.photo), class: "object-cover rounded-md mr-3", width: 100, height: 60 %>
                            <% end %>
                          <% end %>
                          <p class="text-gray-900 whitespace-no-wrap">
                            <%= lesson.title %>
                          </p>
                        </div>
                      </td>
                      <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                        <p class="text-gray-900 whitespace-no-wrap">
                          <%= lesson.created_at %>
                        </p>
                      </td>
                      <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                        <p class="text-gray-900 whitespace-no-wrap">
                          <%= lesson.comments.count %>
                        </p>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </body>
  </div>
</div>

app/views/courses/_progressbar.html.erb
<% if current_user.enroled?(course) %>
  <% progress = current_user.get_enrolment(course).progress %>
  <div class="flex items-center justify-between mt-5">
    <!-- Progress bar -->
    <div class="w-full bg-gray-200 rounded-full">
      <div id="progressBar" class="bg-indigo-700 text-m font-medium text-white text-center p-0.5 leading-none rounded-full" style="width: <%= progress %>%"> <%= progress %>%</div>
    </div>

    <!-- Edit button -->
    <% if params[:authored] %>
      <%= link_to edit_course_path(course) do %>
        <div>
          <button class="flex p-2.5 bg-indigo-700 rounded-xl hover:rounded-3xl hover:bg-indigo-800 transition-all duration-300 text-white ml-3">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
            </svg>
          </button>
        </div>
      <% end %>
    <% end %>
  </div>
<% else %>
  <div class="flex items-center justify-between mt-5">
    <!-- Progress bar -->
    <div class="w-full bg-gray-200 rounded-full">
      <div id="progressBar" class="bg-green-700 text-m font-medium text-white text-center p-0.5 leading-none rounded-full" style="width: 100%"> <%= t :available %> </div>
    </div>

    <!-- Edit button (only shows if authored) -->
    <% if params[:authored] %>
      <%= link_to edit_course_path(course) do %>
        <div>
          <button class="flex p-2.5 bg-indigo-700 rounded-xl hover:rounded-3xl hover:bg-indigo-800 transition-all duration-300 text-white ml-3">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
            </svg>
          </button>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/courses/_sidebar.html.erb
<aside class="sticky top-0 h-screen flex flex-col w-64 px-5 py-8 overflow-y-auto bg-white border-r rtl:border-r-0 rtl:border-l dark:bg-gray-900 dark:border-gray-700">
  <% if @course.photo.representable? %>
    <div class="mt-4">
      <%= image_tag url_for(@course.photo), class: "w-full h-32 object-fill rounded-md" %>
    </div>
  <% end %>
  <div class="flex flex-col justify-between flex-1 mt-6">
    <nav class="-mx-3 space-y-6 ">
      <div class="space-y-3 ">
        <label class="px-3 text-m text-gray-500 dark:text-gray-400"><%= @course.title %></label>
        <%= link_to edit_course_path(@course), class:"flex items-center px-3 py-2 text-gray-600 transition-colors duration-300 transform rounded-lg dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-800 dark:hover:text-gray-200 hover:text-gray-700" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M16.5 3.5l4 4-12 12H4v-4l12-12zm0 0l-4 4m4-4L21 9" />
          </svg>
          <span class="mx-2 text-sm font-medium">Details</span>
        <% end %>
        <%= link_to course_lessons_path(@course), class:"flex items-center px-3 py-2 text-gray-600 transition-colors duration-300 transform rounded-lg dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-800 dark:hover:text-gray-200 hover:text-gray-700" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 4.75h6.5a2 2 0 012 2v12.5a2 2 0 01-2-2h-6.5a2 2 0 00-2 2V6.75a2 2 0 012-2zm10 0h6.5a2 2 0 012 2v12.5a2 2 0 00-2-2h-6.5a2 2 0 012-2V6.75a2 2 0 00-2-2z" />
          </svg>
          <span class="mx-2 text-sm font-medium">Lessons</span>
        <% end %>
        <%= link_to new_course_lesson_path(@course), class:"flex items-center px-3 py-2 text-gray-600 transition-colors duration-300 transform rounded-lg dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-800 dark:hover:text-gray-200 hover:text-gray-700" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
          </svg>
          <span class="mx-2 text-sm font-medium">Add lesson</span>
        <% end %>
      </div>
    </nav>
  </div>
</aside>

app/views/courses/edit.html.erb
<%= render 'pages/navbar' %>
<div class="flex">
  <%= render 'sidebar' %>
  <div class="flex-1 px-8 py-8">
    <div class="bg-white border-4 rounded-lg shadow">
      <%= form_with model: @course do |f| %>
        <div class="flex items-start justify-between p-5 border-b rounded-t sticky top-0 bg-gray-100">
          <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl"><%= "#{t :edit}#{" " + @course.title}" %></h1>
          <%= f.submit "#{t :save}", class:"flex w-auto rounded-lg text-sm p-1.5 ml-auto inline-flex items-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
          <%= link_to course_path(@course), data: {turbo_method: :delete },  class:"text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5  inline-flex items-center" do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="mr-2" fill="red">
              <path d="M3 6v18h18v-18h-18zm5 14c0 .552-.448 1-1 1s-1-.448-1-1v-10c0-.552.448-1 1-1s1 .448 1 1v10zm5 0c0 .552-.448 1-1 1s-1-.448-1-1v-10c0-.552.448-1 1-1s1 .448 1 1v10zm5 0c0 .552-.448 1-1 1s-1-.448-1-1v-10c0-.552.448-1 1-1s1 .448 1 1v10zm4-18v2h-20v-2h5.711c.9 0 1.631-1.099 1.631-2h5.315c0 .901.73 2 1.631 2h5.712z"/>
            </svg>
            <span class="text-gray-600 text-xl"><%= t :delete %></span>
          <% end %>
        </div>
        <div class="p-6 space-y-6">
          <% if @course.errors.any? %>
            <div class="mb-6">
              <ul>
                <% @course.errors.full_messages.each do |message| %>
                  <li>
                    <%= message %>
                  </li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="grid grid-cols-6 gap-6">
            <div class="col-span-6 sm:col-span-3">
              <%= f.label :title, class:"block text-sm mb-2 font-medium text-gray-900" %>
              <%= f.text_field :title, class:"bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" %>
            </div>
            <div class="col-span-6 sm:col-span-3">
              <%= f.label :photo, class:"block text-sm mb-2 font-medium text-gray-900" %>
              <%= f.file_field :photo, class:"bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" %>
            </div>
            <div class="col-span-6 sm:col-span-3">
              <%= f.label :difficulty, class:"block text-sm mb-2 font-medium text-gray-900" %>
              <%= f.select :difficulty, ["Easy", "Medium", "Hard"], {}, class:"bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-1/3 p-2.5" %>
            </div>
            <div class="col-span-6 sm:col-span-3">
              <%= f.label :public, class:"block text-sm mb-2 font-medium text-gray-900" %>
              <%= f.select :public, [true, false], {}, class:"bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-1/3 p-2.5" %>
            </div>
            <div class="col-span-6 sm:col-span-3">
              <%= f.label :tag_list, class:"block text-sm mb-2 font-medium text-gray-900" %>
              <%= f.text_field :tag_list, class:"bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" %>
            </div>
            <div class="col-span-full mb-20">
              <%= f.label :description, class:"block text-sm mb-2 font-medium text-gray-900" %>
              <%= f.rich_text_area :description, class:"bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full h-full p-4" %>
            </div>
            <%= f.text_field :author_id, type: "hidden", value: current_user&.id %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/courses/index.html.erb
<%= render 'pages/navbar' %>
<div class="p-5 lg:px-20 -mt-71 bg-white w-5/6 mx-auto">
  <%= render 'courses', courses: @courses %>
</div>

app/views/courses/show.html.erb
<%= render 'pages/navbar' %>
<div class="flex">
  <div class="flex-1 px-8 py-8">
    <div class="flex justify-center items-center min-h-screen">
      <div class=" mx-auto p-4">
        <div class="bg-white rounded-lg shadow-md flex flex-col justify-between leading-normal p-6 border-4">
          <div class="mb-5">
            <h1 class="text-gray-900 font-bold text-4xl"><%= @course.title %></h1>
            <div class="py-5 text-sm font-regular text-gray-900 flex">
              <div class="flex justify-center">
              <% if current_user.enroled?(@course) %>
                <%= link_to  course_enrolment_path(@course, current_user.get_enrolment(@course)), data: {turbo_method: :delete}, class:"flex items-center px-3 py-2 text-gray-600 transition-colors duration-300 transform rounded-lg dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-800 dark:hover:text-gray-200 hover:text-gray-700" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 4.75h6.5a2 2 0 012 2v12.5a2 2 0 01-2-2h-6.5a2 2 0 00-2 2V6.75a2 2 0 012-2zm10 0h6.5a2 2 0 012 2v12.5a2 2 0 00-2-2h-6.5a2 2 0 012-2V6.75a2 2 0 00-2-2z" />
                  </svg>
                  <span class="mx-2 text-sm font-medium">Abandon</span>
                <% end %>
              <% else %>
                <%= link_to course_enrolments_path(@course, enrolment: {user_id: current_user.id, course_id: @course.id, progress: 0}), data: {turbo_method: :post}, class:"flex items-center px-3 py-2 text-gray-600 transition-colors duration-300 transform rounded-lg dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-800 dark:hover:text-gray-200 hover:text-gray-700" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 4.75h6.5a2 2 0 012 2v12.5a2 2 0 01-2-2h-6.5a2 2 0 00-2 2V6.75a2 2 0 012-2zm10 0h6.5a2 2 0 012 2v12.5a2 2 0 00-2-2h-6.5a2 2 0 012-2V6.75a2 2 0 00-2-2z" />
                  </svg>
                  <span class="mx-2 text-sm font-medium"><%= t :enrol %></span>
                <% end %>
              <% end %>
              </div>
              <span class="mr-3 flex flex-row items-center">
                <svg class="text-indigo-600" fill="currentColor" height="13px" width="13px" viewBox="0 0 512 512">
                  <path d="M256,0C114.837,0,0,114.837,0,256s114.837,256,256,256s256-114.837,256-256S397.163,0,256,0z M277.333,256
			c0,11.797-9.536,21.333-21.333,21.333h-85.333c-11.797,0-21.333-9.536-21.333-21.333s9.536-21.333,21.333-21.333h64v-128
		                   	c0-11.797,9.536-21.333,21.333-21.333s21.333,9.536,21.333,21.333V256z"></path>
                </svg>
                <span class="ml-1"><%= @course.lessons.count %> <%= "#{t :lessons}" %></span>
              </span>
              <a href="#" class="flex flex-row items-center hover:text-indigo-600 mr-3">
                <svg class="text-indigo-600" fill="currentColor" height="16px" aria-hidden="true" role="img" viewBox="0 0 24 24">
                  <path fill="currentColor"
                    d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z">
                  </path>
                </svg>
                <span class="ml-1"><%= @course.author.username %></span>
              </a>
            </div>
            <hr>
            <p class="text-base leading-8 my-5">
              <%= @course.description %>
            </p>
            <%= render 'lessons' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>