config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/hero'

  resources :user_sessions, only: %i[new create destroy]

  resources :users, only: %i[show index new create]

  resources :courses do
    resources :course_lessons, only: %i[update destroy]
    resources :enrolments, only: %i[new create destroy update]
    resources :lessons do
      resources :comments
    end
  end

  
  resources :tags
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :create, User
    return unless user.present?

    can :manage, User
    can :manage, Course, author: user
    can :manage, Lesson
    can :manage, Comment
    can :manage, CourseLesson
    can :read, Course
    can :manage, Enrolment
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :lesson

  validates :body, presence: true, length: { minimum: 1 }
end

app/models/course.rb
class Course < ApplicationRecord
  scope :enroled, ->(user_id) { where(id: Enrolment.where(user_id:).pluck(:course_id)) }
  scope :available, ->(user_id) { where.not(id: enroled(user_id)) }
  scope :authored, ->(user_id) { where(author_id: user_id) }

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :course_lessons, dependent: :destroy
  has_many :lessons, -> { order(:position) }, through: :course_lessons
  has_many :enrolments, dependent: :destroy
  has_one_attached :photo
  has_rich_text :description
  validates :title, presence: true, uniqueness: true, length: { minimum: 3 }
  validates :description, presence: true

  def swap_lessons(first_lesson, second_lesson)
    first_pos = first_lesson.position
    second_pos = second_lesson.position
    first_lesson.set_position(second_pos)
    second_lesson.set_position(first_pos)
  end

  def get_course_lesson(lesson)
    course_lessons.find_by(lesson_id: lesson.id)
  end

  def tag_list
    tags.collect(&:name).join(', ')
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(',').collect { |s| s.strip.downcase }.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name:) }
    self.tags = new_or_found_tags
  end
end

app/models/course_lesson.rb
class CourseLesson < ApplicationRecord
  belongs_to :course
  belongs_to :lesson

  def set_position(position)
    self.position = position
    save
  end
end

app/models/enrolment.rb
class Enrolment < ApplicationRecord
  belongs_to :user
  belongs_to :course

  def update_progress(course, position)
    self.progress = (position.to_f / course.lessons.count * 100).to_i
    save
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  has_many :comments, dependent: :destroy
  has_many :course_lessons, dependent: :destroy
  validates :title, presence: true, length: { minimum: 3 }
  has_rich_text :content
  has_one_attached :photo
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :courses, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :authored_courses, class_name: 'Course', foreign_key: 'author_id', dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :enrolments, dependent: :destroy

  validates :username, presence: true, uniqueness: true, length: { minimum: 1 }
  validates :email, presence: true, uniqueness: true, length: { minimum: 3 }
  validates :password, presence: true, length: { minimum: 3 }
  validates :password_confirmation, presence: true

  def enroled?(course)
    enrolments.pluck(:course_id).include?(course.id)
  end

  def get_enrolment(course)
    enrolments.find_by(course_id: course.id)
  end

  def author?(course)
    id == course.author_id
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    redirect_to courses_path(enroled: true) and return if current_user

    redirect_to pages_hero_path
  end

  def hero; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: login_params[:username])
    if @user&.authenticate(login_params[:password])
      session[:user_id] = @user.id
      redirect_to root_path(enroled: true)
    else
      flash[:alert] = t(:login_alert)
      redirect_to new_user_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def login_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def show; end

  def new; end

  def create
    if @user.save
      flash[:notice] = t(:user_notice)
      redirect_to new_user_session_path
    else
      flash[:alert] = t(:user_alert)
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
  def move_lower
    CourseLesson.swap_lessons(@course.course_lessons.find_by(position: params[:position].to_i),
                              @course.course_lessons.find_by(position: params[:position].to_i - 1))
  end

  def move_higher
    CourseLesson.swap_lessons(@course.course_lessons.find_by(position: params[:position].to_i),
                              @course.course_lessons.find_by(position: params[:position].to_i + 1))
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_courses_helper.rb
module UserCoursesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/user_sessions/new.html.erb
<%= render 'pages/navbar' %>
<div class="flex flex-col lg:flex-row items-center justify-center py-8 mx-auto md:h-screen lg:py-0">
  <div class="w-full h-2/3 bg-gray-100 rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 max-h-[90vh] overflow-auto flex items-center">
    <div class="p-6 space-y-4 md:space-y-6 sm:p-8 w-full">
      <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl">
        <%= t :log_in_accout %>
      </h1>
      <%= form_with model: @user, url: user_sessions_path do |f| %>
        <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
          <div class="mb-6">
            <%= f.label :username, class:"block text-sm mb-2 font-medium text-gray-900" %>
            <%= f.text_field :username, class:"bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" %>
          </div>
          <div class="mb-6">
            <%= f.label :password, class:"block text-sm mb-2 font-medium text-gray-900" %>
            <%= f.password_field :password, class:"bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" %>
          </div>
          <p class="mb-6">
            <%= f.submit "#{t :login}", class:"flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
          </p>
          <p class="text-sm font-light text-gray-500">
            <%= t :dont_have_account %>
            <%= link_to "#{t :sign_up}", new_user_path, class:"font-medium text-indigo-500 no-underline hover:underline" %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
  <div class="lg:flex lg:w-1/2 items-center justify-center min-h-screen">
    <div class="w-full bg-indigo-100 flex items-center justify-center">
      <img src="https://storage.googleapis.com/devitary-image-host.appspot.com/15848031292911696601-undraw_designer_life_w96d.svg"
           class="object-contain h-full w-5/6 p-8">
    </div>
  </div>
</div>